//
//  ImageOrientationTestsStub.c
//  OpenSwiftUISymbolDualTestsSupport

#include "OpenSwiftUIBase.h"

#if OPENSWIFTUI_TARGET_OS_DARWIN

#import <SymbolLocator.h>

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ImageOrientationInitWithExifValue, SwiftUI, $s7SwiftUI5ImageV11OrientationO9exifValueAESgSi_tcfC);

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGSizeApplyImageOrientation, SwiftUI, $sSo6CGSizeV7SwiftUIE5applyyAbC5ImageV11OrientationOF);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGSizeUnapplyImageOrientation, SwiftUI, $sSo6CGSizeV7SwiftUIE7unapplyyAbC5ImageV11OrientationOF);

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGRectApplyImageOrientation, SwiftUI, $sSo6CGRectV7SwiftUIE5apply_2inAbC5ImageV11OrientationO_So6CGSizeVtF);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGRectUnapplyImageOrientation, SwiftUI, $sSo6CGRectV7SwiftUIE7unapply_2inAbC5ImageV11OrientationO_So6CGSizeVtF);

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGAffineTransformInitWithImageOrientationInSize, SwiftUI, $sSo17CGAffineTransformV7SwiftUIE11orientation2inAbC5ImageV11OrientationO_So6CGSizeVtcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGAffineTransformInitWithImageOrientationInRect, SwiftUI, $sSo17CGAffineTransformV7SwiftUIE11orientation2inAbC5ImageV11OrientationO_So6CGRectVtcfC);

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGAffineTransformApplyImageOrientationWithSize, SwiftUI, $sSo17CGAffineTransformV7SwiftUIE5apply_2inyAC5ImageV11OrientationO_So6CGSizeVtF);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_CGAffineTransformApplyImageOrientation, SwiftUI, $sSo17CGAffineTransformV7SwiftUIE5applyyyAC5ImageV11OrientationOF);

#endif
