name: Run UI Tests
description: Execute UI tests and collect artifacts if failure

inputs:
  platform:
    description: 'Platform to test (ios or macos)'
    required: true
  destination:
    description: 'xcodebuild destination parameter'
    required: true
  artifact-name:
    description: 'Name for the artifact upload'
    required: true

outputs:
  test-result:
    description: 'Test execution result (success or failure)'
    value: ${{ steps.uitest.outcome }}

runs:
  using: composite
  steps:
    - name: Install xcbeautify
      shell: bash
      run: brew install xcbeautify

    - name: Record baseline images with SwiftUI
      shell: bash
      run: |
        cd Example
        set -o pipefail
        xcodebuild test \
          -scheme SUI_UITests \
          -destination "${{ inputs.destination }}" \
          -skipMacroValidation \
          -skipPackagePluginValidation \
          | xcbeautify --renderer github-actions || true

    - name: Run UI tests with OpenSwiftUI
      id: uitest
      continue-on-error: true
      shell: bash
      run: |
        cd Example
        set -o pipefail
        xcodebuild test \
          -scheme OSUI_UITests \
          -destination "${{ inputs.destination }}" \
          -skipMacroValidation \
          -skipPackagePluginValidation 2>&1 | tee /tmp/${{ inputs.platform }}-uitest.log | xcbeautify --renderer github-actions

    - name: Collect failed snapshots
      if: steps.uitest.outcome == 'failure'
      shell: bash
      run: |
        Scripts/CI/collect_uitest_failures.sh /tmp/${{ inputs.platform }}-uitest.log /tmp/uitest-artifacts

    - name: Upload test artifacts
      if: steps.uitest.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/uitest-artifacts/
        retention-days: 7
