//
//  _UIConstraintBasedLayoutHostingView.swift
//  OpenSwiftUI_SPI
//
//  Generated by `ipsw class-dump UIKitCore --headers`

//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.621, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: iOsSimulator, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 8506.1.101.0.0
//
#ifndef _UIConstraintBasedLayoutHostingView_h
#define _UIConstraintBasedLayoutHostingView_h

#include "OpenSwiftUIBase.h"

#if __has_include(<UIKit/UIKit.h>)

#include <UIKit/UIKit.h>

typedef struct BaselineOffset {
    CGFloat firstTextBaseline;
    CGFloat lastTextBaseline;
} BaselineOffset;

@interface _UIConstraintBasedLayoutHostingView : UIView {
    /* instance variables */
    BOOL _hasAddedConstraints;
}

@property (retain, nonatomic, nullable) UIView *hostedView;

/* class methods */
+ (BOOL)requiresConstraintBasedLayout;

/* instance methods */
- (id)initWithHostedView:(id)view;
- (void)willRemoveSubview:(id)subview;
- (void)_setFrameWithAlignmentRect:(CGRect)rect;
- (void)_intrinsicContentSizeInvalidatedForChildView:(id)view;
- (void)constraintsDidChangeInEngine:(id)engine;
- (void)_scheduleUpdateConstraintsPassAsEngineHostNeedingLayout:(BOOL)layout;
- (void)_layoutMetricsInvalidatedForHostedView;
- (void)updateConstraints;
- (UIEdgeInsets)alignmentRectInsets;
- (BOOL)_layoutHeightDependsOnWidth;
- (BaselineOffset)_baselineOffsetsAtSize:(CGSize)size;
- (CGSize)sizeThatFits:(CGSize)fits;
- (CGSize)_layoutSizeThatFits:(CGSize)fits fixedAxes:(unsigned long long)axes;

@end

#endif /* __has_include(<UIKit/UIKit.h>) */

#endif /* _UIConstraintBasedLayoutHostingView_h */
