[tools]
tuist = "4.202.5"

[env]
TUIST_USE_SWIFTERPM=1
OPENSWIFTUI_OPENATTRIBUTESHIMS_ATTRIBUTEGRAPH = "0"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE = "1"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY = "0"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY_VERSION = "0.4.1"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_SOURCE_VERSION = "0.4.1-bugfix.2"
# OPENSWIFTUI_USE_LOCAL_DEPS = "1"
