[tools]
tuist = "4.206.0"

[env]
TUIST_USE_SWIFTERPM=1
OPENSWIFTUI_OPENATTRIBUTESHIMS_ATTRIBUTEGRAPH = "0"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE = "1"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY = "1"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY_VERSION = "0.5.2"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY_CHECKSUM = "0eca53a3620776cffcc3d2047d11efaf893b53078b95e59e793f86caa3f2c169"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_SOURCE_VERSION = "0.5.2"
# OPENSWIFTUI_USE_LOCAL_DEPS = "1"
