[tools]
tuist = "4.192.0"

[env]
OPENSWIFTUI_LIBRARY_TYPE = "dynamic"
OPENSWIFTUI_OPENATTRIBUTESHIMS_ATTRIBUTEGRAPH = "1"
OPENSWIFTUI_USE_LOCAL_DEPS = "1"
# workaround for tuist generate issue
TUIST_OPENSWIFTUI_LIBRARY_TYPE = "dynamic"
TUIST_OPENSWIFTUI_OPENATTRIBUTESHIMS_ATTRIBUTEGRAPH = "1"
TUIST_OPENSWIFTUI_USE_LOCAL_DEPS = "1"
