[tools]
tuist = "4.206.0"

[env]
TUIST_USE_SWIFTERPM=1
OPENSWIFTUI_OPENATTRIBUTESHIMS_ATTRIBUTEGRAPH = "0"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE = "1"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY = { default = "1" }
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY_VERSION = "0.6.0"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_BINARY_CHECKSUM = "4ed9025d23aa3521a37a52df3ec592850f04238dd650fc06b23d887d69d90b7b"
OPENSWIFTUI_OPENATTRIBUTESHIMS_COMPUTE_SOURCE_VERSION = "0.6.0"
# OPENSWIFTUI_USE_LOCAL_DEPS = "1"
