/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 6:51:04 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#ifndef LSApplicationWorkspace_h
#define LSApplicationWorkspace_h

#include "OpenSwiftUIBase.h"

#if __has_include(<UIKit/UIKit.h>)

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "LSOpenConfiguration.h"

NS_ASSUME_NONNULL_BEGIN

@interface LSApplicationWorkspace : NSObject
+(nullable instancetype)defaultWorkspace;
-(void)openURL:(NSURL *)url configuration:(_LSOpenConfiguration *)config completionHandler:(void (^)(BOOL))completion;
@end

NS_ASSUME_NONNULL_END

#endif /* UIKit.h */

#endif /* LSApplicationWorkspace_h */
