/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 6:51:04 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/Frameworks/CoreServices.framework/CoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#ifndef LSOpenConfiguration_h
#define LSOpenConfiguration_h

#include "OpenSwiftUIBase.h"

#if __has_include(<UIKit/UIKit.h>)

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface _LSOpenConfiguration : NSObject
@property(assign, getter=isSensitive,nonatomic) BOOL sensitive;
@property(nonatomic, retain, nullable) id targetConnectionEndpoint;
-(instancetype)init;
-(BOOL)isSensitive;
-(void)setSensitive:(BOOL)sensitive;
-(void)setTargetConnectionEndpoint:(nullable id)endpoint ;
-(nullable id)targetConnectionEndpoint;
@end

NS_ASSUME_NONNULL_END

#endif /* UIKit.h */

#endif /* LSOpenConfiguration_h */
