//
//  AXAutomationType.h
//  OpenSwiftUI_SPI
//
//  Audited for 6.5.4
//  Status: WIP

#ifndef AXAutomationType_h
#define AXAutomationType_h

#include "OpenSwiftUIBase.h"

// Names follow the corresponding automation roles. Values differ from XCUIElementType.
typedef OPENSWIFTUI_ENUM(uint64_t, AXAutomationType) {
    AXAutomationTypeUnknown = 0,
    AXAutomationTypeApplication = 1,
    AXAutomationTypeWindow = 2,
    AXAutomationTypeSheet = 3,
    AXAutomationTypeDrawer = 4,
    AXAutomationTypeGroup = 5,
    AXAutomationTypeAlert = 6,
    AXAutomationTypeDialog = 7,
    AXAutomationTypeBannerNotification = 8,
    AXAutomationTypeButton = 9,
    AXAutomationTypeRadioButton = 10,
    AXAutomationTypeRadioGroup = 11,
    AXAutomationTypeCheckBox = 12,
    AXAutomationTypeDisclosureTriangle = 13,
    AXAutomationTypePopUpButton = 14,
    AXAutomationTypeComboBox = 15,
    AXAutomationTypeMenuButton = 16,
    AXAutomationTypeToolbarButton = 17,
    AXAutomationTypePopover = 18,
    AXAutomationTypeKeyboard = 19,
    AXAutomationTypeKey = 20,
    AXAutomationTypeNavigationBar = 21,
    AXAutomationTypeTabBar = 22,
    AXAutomationTypeTabGroup = 23,
    AXAutomationTypeToolbar = 24,
    AXAutomationTypeStatusBar = 25,
    AXAutomationTypeTable = 26,
    AXAutomationTypeTableRow = 27,
    AXAutomationTypeTableColumn = 28,
    AXAutomationTypeOutline = 29,
    AXAutomationTypeOutlineRow = 30,
    AXAutomationTypeBrowser = 31,
    AXAutomationTypeCollectionView = 32,
    AXAutomationTypeSlider = 33,
    AXAutomationTypePageIndicator = 34,
    AXAutomationTypeProgressIndicator = 35,
    AXAutomationTypeActivityIndicator = 36,
    AXAutomationTypeSegmentedControl = 37,
    AXAutomationTypePicker = 38,
    AXAutomationTypePickerWheel = 39,
    AXAutomationTypeSwitch = 40,
    AXAutomationTypeToggle = 41,
    AXAutomationTypeLink = 42,
    AXAutomationTypeImage = 43,
    AXAutomationTypeIcon = 44,
    AXAutomationTypeSearchField = 45,
    AXAutomationTypeScrollView = 46,
    AXAutomationTypeScrollBar = 47,
    AXAutomationTypeStaticText = 48,
    AXAutomationTypeTextField = 49,
    AXAutomationTypeSecureTextField = 50,
    AXAutomationTypeDatePicker = 51,
    AXAutomationTypeTextView = 52,
    AXAutomationTypeMenu = 53,
    AXAutomationTypeMenuItem = 54,
    AXAutomationTypeMenuBar = 55,
    AXAutomationTypeMenuBarItem = 56,
    AXAutomationTypeMap = 57,
    AXAutomationTypeWebView = 58,
    AXAutomationTypeIncrementArrow = 59,
    AXAutomationTypeDecrementArrow = 60,
    AXAutomationTypeTimeline = 61,
    AXAutomationTypeRatingIndicator = 62,
    AXAutomationTypeValueIndicator = 63,
    AXAutomationTypeSplitGroup = 64,
    AXAutomationTypeSplitter = 65,
    AXAutomationTypeRelevanceIndicator = 66,
    AXAutomationTypeColorWell = 67,
    AXAutomationTypeHelpTag = 68,
    AXAutomationTypeMatte = 69,
    AXAutomationTypeDockItem = 70,
    AXAutomationTypeRuler = 71,
    AXAutomationTypeRulerMarker = 72,
    AXAutomationTypeGrid = 73,
    AXAutomationTypeLevelIndicator = 74,
    AXAutomationTypeCell = 75,
    AXAutomationTypeLayoutArea = 76,
    AXAutomationTypeLayoutItem = 77,
    AXAutomationTypeHandle = 78,
    AXAutomationTypeStepper = 79,
    AXAutomationTypeTab = 80,
    AXAutomationTypeTouchBar = 81,
    AXAutomationTypeStatusItem = 82,
    AXAutomationTypeOther = 83,
    // TODO: Identify the distinct button roles at values 84 through 88.
};

#endif /* AXAutomationType_h */
