//
//  ColorMatrixTestsStub.c
//  OpenSwiftUISymbolDualTestsSupport

#include "OpenSwiftUIBase.h"

#if OPENSWIFTUI_TARGET_OS_DARWIN

#import <SymbolLocator.h>

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitIdentity, SwiftUICore, $s7SwiftUI12_ColorMatrixVACycfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitColorMatrix, SwiftUICore, $s7SwiftUI12_ColorMatrixVyAcA0cD0VcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitRows, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE4row14row24row34row4ACSf_S4ft_Sf_S4ftSf_S4ftSf_S4fttcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitGraphicsFilter, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE_13premultipliedACSgAA14GraphicsFilterO_SbtcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixMultiply, SwiftUICore, $s7SwiftUI12_ColorMatrixV1moiyA2C_ACtFZ);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixIsIdentity, SwiftUICore, $s7SwiftUI12_ColorMatrixV10isIdentitySbvg);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitColorMultiply, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE13colorMultiply13premultipliedAcA0C0V8ResolvedV_SbtcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitHueRotation, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE11hueRotationAcA5AngleV_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitBrightness, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE10brightnessACSd_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitContrast, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE8contrastACSd_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitLuminanceToAlpha, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE16luminanceToAlphaACyt_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitColorInvert, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE11colorInvertACSf_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitColorMonochrome, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE15colorMonochrome6amount4biasAcA0C0V8ResolvedV_S2ftcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixInitFloatArray, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE10floatArrayACSaySfG_tcfC);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_ColorMatrixFloatArray, SwiftUICore, $s7SwiftUI12_ColorMatrixVAAE10floatArraySaySfGvg);

#endif
