//
//  GraphicsContextTestsStub.c
//  OpenSwiftUISymbolDualTestsSupport

#include "OpenSwiftUIBase.h"

#if OPENSWIFTUI_SWIFTUI_RENDERER

#import <SymbolLocator.h>

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_GraphicsContextDrawPathWithShadingAndStyle, SwiftUI, $s7SwiftUI15GraphicsContextVAAE4draw_4with5styleyAA4PathV_AC15ResolvedShadingOAA0H12DrawingStyleOtF);
DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_GraphicsContextDrawImageInRectStyleShading, SwiftUI, $s7SwiftUI15GraphicsContextVAAE4draw_2in5style7shadingyAA0C5ImageV_So6CGRectVAA9FillStyleVAC7ShadingVSgtF);

#endif
