//
//  DisplayListViewRenderer+TestStub.c
//  OpenSwiftUISymbolDualTestsSupport

#include "OpenSwiftUIBase.h"

#if OPENSWIFTUI_TARGET_OS_DARWIN && _OPENSWIFTUI_SWIFTUI_RENDER

#import <SymbolLocator.h>

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_DisplayListViewRendererRenderRootView, SwiftUI, $s7SwiftUI11DisplayListVAAE12ViewRendererC6render04rootE04from4time8nextTime7version10maxVersion11environmentAA0L0VyXl_Ac2oC0O0VAqE11EnvironmentVtF);

DEFINE_SL_STUB_SLF(OpenSwiftUITestStub_DisplayListViewRendererRenderAsync, SwiftUI, $s7SwiftUI11DisplayListVAAE12ViewRendererC11renderAsync2to4time8nextTime15targetTimestamp7version10maxVersionAA0L0VSgAC_A2noC0Q0VAQtF);

#endif
