//
//  AXOpenSwiftUITraits.h
//  OpenSwiftUI_SPI
//
//  Audited for 6.5.4
//  Status: Complete

#ifndef AXOpenSwiftUITraits_h
#define AXOpenSwiftUITraits_h

#include "OpenSwiftUIBase.h"

OPENSWIFTUI_EXTERN_C_BEGIN

typedef uint64_t AXOpenSwiftUITraits OPENSWIFTUI_SWIFT_STRUCT;

OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsNone;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsButton;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsLink;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsImage;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSelected;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsPlaysSound;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsKeyboardKey;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsStaticText;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSummaryElement;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsNotEnabled;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsUpdatesFrequently;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSearchField;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsStartsMediaSession;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAdjustable;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAllowsDirectInteraction;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsCausesPageTurn;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTabBar;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsHeader;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsWebContent;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTextEntry;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsPickerElement;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsRadioButton;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsIsEditing;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsLaunchIcon;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsStatusBarElement;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSecureTextField;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsInactive;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsFooter;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsBackButton;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTabButton;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAutoCorrectCandidate;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsDeleteKey;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSelectionDismissesItem;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsVisited;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsScrollable;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSpacer;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTableIndex;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsMap;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTextOperationsAvailable;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsDraggable;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsGesturePracticeRegion;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsPopupButton;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAllowsNativeSliding;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsMathEquation;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsContainedByTable;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsContainedByList;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTouchContainer;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSupportsZoom;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsTextArea;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsBookContent;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsContainedByLandmark;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsFolderIcon;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsReadOnly;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsMenuItem;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsToggle;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsIgnoreItemChooser;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsSupportsTrackingDetail;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAlert;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsContainedByFieldset;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsAllowsLayoutChangeInStatusBar;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsWebInteractiveVideo;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsProminentIcon;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsGestureHandlerRegion;
OPENSWIFTUI_EXPORT const AXOpenSwiftUITraits AXOpenSwiftUITraitsRemoveTraitsSentinel;

OPENSWIFTUI_EXTERN_C_END

#endif /* AXOpenSwiftUITraits_h */
