/*
* This header is generated by classdump-dyld 1.0
* on Friday, January 21, 2022 at 8:58:16 AM Pacific Standard Time
* Operating System: Version 15.2.1 (Build 19C63)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@interface UIScene (OpenSwiftUI)
-(nullable id)_currentOpenApplicationEndpoint;
@end
