//
//  _NSConstraintBasedLayoutHostingView.h
//  OpenSwiftUI_SPI
//
//  Generated by `ipsw class-dump /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e 'AppKit' --headers`

//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.621, BuildCommit: Homebrew)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.5, SDK: 18.5, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 2575.60.5.0.0
//
#ifndef _NSConstraintBasedLayoutHostingView_h
#define _NSConstraintBasedLayoutHostingView_h

#include "OpenSwiftUIBase.h"

#if __has_include(<AppKit/AppKit.h>)

#include <AppKit/AppKit.h>

@interface _NSConstraintBasedLayoutHostingView : NSView {
    /* instance variables */
    BOOL _hasAddedConstraints;
}

@property (retain, nullable) NSView *hostedView;

/* class methods */
+ (BOOL)requiresConstraintBasedLayout;

/* instance methods */
- (void)dealloc;
- (CGPoint)_baselineOffsetsAtSize:(CGSize)size;
- (void)_informContainerThatSubviewsNeedUpdateConstraints;
- (void)_intrinsicContentSizeInvalidatedForChildView:(id)view;
- (BOOL)_layoutHeightDependsOnWidth;
- (void)_layoutMetricsInvalidatedForHostedView;
- (CGSize)_layoutSizeThatFits:(CGSize)fits fixedAxes:(unsigned long long)axes;
- (void)_setFrameWithAlignmentRect:(CGRect)rect;
- (NSEdgeInsets)alignmentRectInsets;
- (void)constraintsDidChangeInEngine:(id)engine;
- (id)initWithHostedView:(id)view;
- (CGSize)sizeThatFits:(CGSize)fits;
- (void)sizeToFit;
- (void)updateConstraints;
- (void)willRemoveSubview:(id)subview;

@end

#endif /* __has_include(<AppKit/AppKit.h>) */

#endif /* _NSConstraintBasedLayoutHostingView_h */
