name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests for macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: ["16.4"]
        release: [2024]
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENATTRIBUTEGRAPH_ATTRIBUTEGRAPH: 1
      OPENSWIFTUI_SWIFT_LOG: 0
      OPENSWIFTUI_SWIFT_CRYPTO: 0
      OPENSWIFTUI_TARGET_RELEASE: ${{ matrix.release }}
      OPENSWIFTUI_USE_LOCAL_DEPS: 1
      OPENATTRIBUTEGRAPH_USE_LOCAL_DEPS: 1
      OPENATTRIBUTEGRAPH_TARGET_RELEASE: ${{ matrix.release }}
      OPENRENDERBOX_USE_LOCAL_DEPS: 1
      OPENRENDERBOX_TARGET_RELEASE: ${{ matrix.release }}
      DARWIN_PRIVATE_FRAMEWORKS_TARGET_RELEASE: ${{ matrix.release }}
      OPENSWIFTUI_LINK_TESTING: 1
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Set up build environment
        run: Scripts/CI/darwin_setup_build.sh
        shell: bash
      - name: Run compatibility tests on OpenSwiftUI + macOS
        run: |
          swift test \
            --filter OpenSwiftUICompatibilityTests \
            --build-path .build-compatibility-test-debug
        env:
          OPENSWIFTUI_COMPATIBILITY_TEST: 0
      - name: Run compatibility tests on SwiftUI + macOS
        run: |
          swift test \
            --filter OpenSwiftUICompatibilityTests \
            --build-path .build-compatibility-test-debug
        env:
          OPENSWIFTUI_COMPATIBILITY_TEST: 1
  compatibility_tests_ios:
    name: Execute compatibility tests for iOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: ["16.4"]
        release: [2024]
        ios-version: ["18.5"]
        include:
          - ios-version: "18.5"
            ios-simulator-name: "iPhone 16 Pro"
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENATTRIBUTEGRAPH_ATTRIBUTEGRAPH: 1
      OPENSWIFTUI_SWIFT_LOG: 0
      OPENSWIFTUI_SWIFT_CRYPTO: 0
      OPENSWIFTUI_TARGET_RELEASE: ${{ matrix.release }}
      OPENSWIFTUI_SUPPORT_MULTI_PRODUCTS: 0
      OPENSWIFTUI_USE_LOCAL_DEPS: 1
      OPENATTRIBUTEGRAPH_USE_LOCAL_DEPS: 1
      OPENATTRIBUTEGRAPH_TARGET_RELEASE: ${{ matrix.release }}
      OPENRENDERBOX_USE_LOCAL_DEPS: 1
      OPENRENDERBOX_TARGET_RELEASE: ${{ matrix.release }}
      DARWIN_PRIVATE_FRAMEWORKS_TARGET_RELEASE: ${{ matrix.release }}
      OPENSWIFTUI_LINK_TESTING: 1
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: ./.github/actions/setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Set up build environment
        run: Scripts/CI/darwin_setup_build.sh
        shell: bash
      - name: Run compatibility tests on OpenSwiftUI + iOS
        run: |
          xcodebuild test \
          -scheme OpenSwiftUI \
          -configuration Debug \
          -destination "platform=iOS Simulator,OS=${{ matrix.ios-version }},name=${{ matrix.ios-simulator-name }}" \
          -only-testing:OpenSwiftUICompatibilityTests \
          -skipMacroValidation \
          -skipPackagePluginValidation
        env:
          OPENSWIFTUI_COMPATIBILITY_TEST: 0
      - name: Run compatibility tests on SwiftUI + iOS
        run: |
          xcodebuild test \
          -scheme OpenSwiftUI \
          -configuration Debug \
          -destination "platform=iOS Simulator,OS=${{ matrix.ios-version }},name=${{ matrix.ios-simulator-name }}" \
          -only-testing:OpenSwiftUICompatibilityTests \
          -skipMacroValidation \
          -skipPackagePluginValidation
        env:
          OPENSWIFTUI_COMPATIBILITY_TEST: 1