name: Issue Triage

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

permissions:
  contents: read
  issues: write

jobs:
  triage-issue:
    uses: OpenSwiftUIProject/github-workflows/.github/workflows/issue-triage.yml@main
    with:
      # fromJSON workaround number inputs: https://github.com/orgs/community/discussions/67182#discussioncomment-8617964
      issue_number: ${{ fromJSON(inputs.issue_number) }}
    secrets: inherit
