name: Issue Triage

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  triage-issue:
    uses: OpenSwiftUIProject/github-workflows/.github/workflows/issue-triage.yml@main
    secrets: inherit
