name: PR Triage

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to triage'
        required: true
        type: number

permissions:
  contents: read
  pull-requests: write

jobs:
  triage-pr:
    uses: OpenSwiftUIProject/github-workflows/.github/workflows/pr-triage.yml@main
    with:
      # fromJSON workaround number inputs: https://github.com/orgs/community/discussions/67182#discussioncomment-8617964
      pr_number: ${{ inputs.pr_number && fromJSON(inputs.pr_number) || github.event.pull_request.number }}
    secrets: inherit
