name: PR Triage

on:
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage-pr:
    uses: OpenSwiftUIProject/github-workflows/.github/workflows/pr-triage.yml@main
    secrets: inherit
