name: PR Triage

on:
  pull_request_target:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to triage'
        required: true
        type: number

permissions:
  contents: read
  pull-requests: write

jobs:
  triage-pr:
    uses: OpenSwiftUIProject/github-workflows/.github/workflows/pr-triage.yml@main
    secrets: inherit
